# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'metsens_design.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1319, 769)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.topGridLayout = QtWidgets.QGridLayout()
        self.topGridLayout.setObjectName("topGridLayout")
        self.topHorizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.topHorizontalLayout_4.setObjectName("topHorizontalLayout_4")
        self.topGridLayout.addLayout(self.topHorizontalLayout_4, 0, 3, 1, 1)
        self.topHorizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.topHorizontalLayout_5.setObjectName("topHorizontalLayout_5")
        self.topPushButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.topPushButton.sizePolicy().hasHeightForWidth())
        self.topPushButton.setSizePolicy(sizePolicy)
        self.topPushButton.setMaximumSize(QtCore.QSize(80, 25))
        self.topPushButton.setObjectName("topPushButton")
        self.topHorizontalLayout_5.addWidget(self.topPushButton)
        self.topPushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.topPushButton_2.sizePolicy().hasHeightForWidth())
        self.topPushButton_2.setSizePolicy(sizePolicy)
        self.topPushButton_2.setMaximumSize(QtCore.QSize(80, 25))
        self.topPushButton_2.setObjectName("topPushButton_2")
        self.topHorizontalLayout_5.addWidget(self.topPushButton_2)
        self.resetButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.resetButton.sizePolicy().hasHeightForWidth())
        self.resetButton.setSizePolicy(sizePolicy)
        self.resetButton.setMaximumSize(QtCore.QSize(80, 25))
        self.resetButton.setObjectName("resetButton")
        self.topHorizontalLayout_5.addWidget(self.resetButton)
        self.topGridLayout.addLayout(self.topHorizontalLayout_5, 0, 4, 1, 1)
        self.topHorizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.topHorizontalLayout_3.setObjectName("topHorizontalLayout_3")
        self.setportBox = QtWidgets.QComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.setportBox.sizePolicy().hasHeightForWidth())
        self.setportBox.setSizePolicy(sizePolicy)
        self.setportBox.setMinimumSize(QtCore.QSize(80, 0))
        self.setportBox.setMaximumSize(QtCore.QSize(100, 16777215))
        self.setportBox.setObjectName("setportBox")
        self.topHorizontalLayout_3.addWidget(self.setportBox)
        self.baudBox = QtWidgets.QComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.baudBox.sizePolicy().hasHeightForWidth())
        self.baudBox.setSizePolicy(sizePolicy)
        self.baudBox.setMinimumSize(QtCore.QSize(80, 0))
        self.baudBox.setMaximumSize(QtCore.QSize(80, 16777215))
        self.baudBox.setObjectName("baudBox")
        self.topHorizontalLayout_3.addWidget(self.baudBox)
        self.byteBox = QtWidgets.QComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.byteBox.sizePolicy().hasHeightForWidth())
        self.byteBox.setSizePolicy(sizePolicy)
        self.byteBox.setMinimumSize(QtCore.QSize(80, 0))
        self.byteBox.setMaximumSize(QtCore.QSize(80, 16777215))
        self.byteBox.setObjectName("byteBox")
        self.topHorizontalLayout_3.addWidget(self.byteBox)
        self.parityBox = QtWidgets.QComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.parityBox.sizePolicy().hasHeightForWidth())
        self.parityBox.setSizePolicy(sizePolicy)
        self.parityBox.setMinimumSize(QtCore.QSize(80, 0))
        self.parityBox.setMaximumSize(QtCore.QSize(80, 16777215))
        self.parityBox.setObjectName("parityBox")
        self.topHorizontalLayout_3.addWidget(self.parityBox)
        self.stopbitBox = QtWidgets.QComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stopbitBox.sizePolicy().hasHeightForWidth())
        self.stopbitBox.setSizePolicy(sizePolicy)
        self.stopbitBox.setMinimumSize(QtCore.QSize(80, 0))
        self.stopbitBox.setMaximumSize(QtCore.QSize(80, 16777215))
        self.stopbitBox.setObjectName("stopbitBox")
        self.topHorizontalLayout_3.addWidget(self.stopbitBox)
        self.senstypeBox = QtWidgets.QComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.senstypeBox.sizePolicy().hasHeightForWidth())
        self.senstypeBox.setSizePolicy(sizePolicy)
        self.senstypeBox.setMinimumSize(QtCore.QSize(80, 0))
        self.senstypeBox.setMaximumSize(QtCore.QSize(80, 16777215))
        self.senstypeBox.setObjectName("senstypeBox")
        self.topHorizontalLayout_3.addWidget(self.senstypeBox)
        self.applyButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.applyButton.sizePolicy().hasHeightForWidth())
        self.applyButton.setSizePolicy(sizePolicy)
        self.applyButton.setMaximumSize(QtCore.QSize(80, 25))
        self.applyButton.setObjectName("applyButton")
        self.topHorizontalLayout_3.addWidget(self.applyButton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.topHorizontalLayout_3.addItem(spacerItem)
        self.topGridLayout.addLayout(self.topHorizontalLayout_3, 0, 2, 1, 1)
        self.topHorizontalLayout = QtWidgets.QHBoxLayout()
        self.topHorizontalLayout.setObjectName("topHorizontalLayout")
        self.timeLabel = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.timeLabel.sizePolicy().hasHeightForWidth())
        self.timeLabel.setSizePolicy(sizePolicy)
        self.timeLabel.setMinimumSize(QtCore.QSize(100, 0))
        self.timeLabel.setMaximumSize(QtCore.QSize(200, 25))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.timeLabel.setFont(font)
        self.timeLabel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.timeLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.timeLabel.setObjectName("timeLabel")
        self.topHorizontalLayout.addWidget(self.timeLabel)
        self.topGridLayout.addLayout(self.topHorizontalLayout, 0, 0, 1, 1)
        self.topText = QtWidgets.QTextEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.topText.sizePolicy().hasHeightForWidth())
        self.topText.setSizePolicy(sizePolicy)
        self.topText.setMaximumSize(QtCore.QSize(300, 25))
        self.topText.setObjectName("topText")
        self.topGridLayout.addWidget(self.topText, 0, 1, 1, 1)
        self.gridLayout_6.addLayout(self.topGridLayout, 1, 0, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.portBox_9 = QtWidgets.QComboBox(self.centralwidget)
        self.portBox_9.setMaximumSize(QtCore.QSize(100, 16777215))
        self.portBox_9.setObjectName("portBox_9")
        self.horizontalLayout_9.addWidget(self.portBox_9)
        self.nameButton_9 = QtWidgets.QPushButton(self.centralwidget)
        self.nameButton_9.setObjectName("nameButton_9")
        self.horizontalLayout_9.addWidget(self.nameButton_9)
        self.sendButton_9 = QtWidgets.QPushButton(self.centralwidget)
        self.sendButton_9.setMaximumSize(QtCore.QSize(40, 16777215))
        self.sendButton_9.setObjectName("sendButton_9")
        self.horizontalLayout_9.addWidget(self.sendButton_9)
        self.muteButton_9 = QtWidgets.QPushButton(self.centralwidget)
        self.muteButton_9.setMaximumSize(QtCore.QSize(40, 16777215))
        self.muteButton_9.setObjectName("muteButton_9")
        self.horizontalLayout_9.addWidget(self.muteButton_9)
        self.gridLayout_3.addLayout(self.horizontalLayout_9, 2, 0, 1, 1)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.portBox_10 = QtWidgets.QComboBox(self.centralwidget)
        self.portBox_10.setMaximumSize(QtCore.QSize(100, 16777215))
        self.portBox_10.setObjectName("portBox_10")
        self.horizontalLayout_10.addWidget(self.portBox_10)
        self.nameButton_10 = QtWidgets.QPushButton(self.centralwidget)
        self.nameButton_10.setObjectName("nameButton_10")
        self.horizontalLayout_10.addWidget(self.nameButton_10)
        self.sendButton_10 = QtWidgets.QPushButton(self.centralwidget)
        self.sendButton_10.setMaximumSize(QtCore.QSize(40, 16777215))
        self.sendButton_10.setObjectName("sendButton_10")
        self.horizontalLayout_10.addWidget(self.sendButton_10)
        self.muteButton_10 = QtWidgets.QPushButton(self.centralwidget)
        self.muteButton_10.setMaximumSize(QtCore.QSize(40, 16777215))
        self.muteButton_10.setObjectName("muteButton_10")
        self.horizontalLayout_10.addWidget(self.muteButton_10)
        self.gridLayout_3.addLayout(self.horizontalLayout_10, 2, 1, 1, 1)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.portBox_11 = QtWidgets.QComboBox(self.centralwidget)
        self.portBox_11.setMaximumSize(QtCore.QSize(100, 16777215))
        self.portBox_11.setObjectName("portBox_11")
        self.horizontalLayout_11.addWidget(self.portBox_11)
        self.nameButton_11 = QtWidgets.QPushButton(self.centralwidget)
        self.nameButton_11.setObjectName("nameButton_11")
        self.horizontalLayout_11.addWidget(self.nameButton_11)
        self.sendButton_11 = QtWidgets.QPushButton(self.centralwidget)
        self.sendButton_11.setMaximumSize(QtCore.QSize(40, 16777215))
        self.sendButton_11.setObjectName("sendButton_11")
        self.horizontalLayout_11.addWidget(self.sendButton_11)
        self.muteButton_11 = QtWidgets.QPushButton(self.centralwidget)
        self.muteButton_11.setMaximumSize(QtCore.QSize(40, 16777215))
        self.muteButton_11.setObjectName("muteButton_11")
        self.horizontalLayout_11.addWidget(self.muteButton_11)
        self.gridLayout_3.addLayout(self.horizontalLayout_11, 2, 2, 1, 1)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.portBox_12 = QtWidgets.QComboBox(self.centralwidget)
        self.portBox_12.setMaximumSize(QtCore.QSize(100, 16777215))
        self.portBox_12.setObjectName("portBox_12")
        self.horizontalLayout_12.addWidget(self.portBox_12)
        self.nameButton_12 = QtWidgets.QPushButton(self.centralwidget)
        self.nameButton_12.setObjectName("nameButton_12")
        self.horizontalLayout_12.addWidget(self.nameButton_12)
        self.sendButton_12 = QtWidgets.QPushButton(self.centralwidget)
        self.sendButton_12.setMaximumSize(QtCore.QSize(40, 16777215))
        self.sendButton_12.setObjectName("sendButton_12")
        self.horizontalLayout_12.addWidget(self.sendButton_12)
        self.muteButton_12 = QtWidgets.QPushButton(self.centralwidget)
        self.muteButton_12.setMaximumSize(QtCore.QSize(40, 16777215))
        self.muteButton_12.setObjectName("muteButton_12")
        self.horizontalLayout_12.addWidget(self.muteButton_12)
        self.gridLayout_3.addLayout(self.horizontalLayout_12, 2, 3, 1, 1)
        self.valueLabel_9 = QtWidgets.QLabel(self.centralwidget)
        self.valueLabel_9.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.valueLabel_9.setFont(font)
        self.valueLabel_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.valueLabel_9.setAlignment(QtCore.Qt.AlignCenter)
        self.valueLabel_9.setObjectName("valueLabel_9")
        self.gridLayout_3.addWidget(self.valueLabel_9, 0, 0, 1, 1)
        self.valueLabel_10 = QtWidgets.QLabel(self.centralwidget)
        self.valueLabel_10.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.valueLabel_10.setFont(font)
        self.valueLabel_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.valueLabel_10.setAlignment(QtCore.Qt.AlignCenter)
        self.valueLabel_10.setObjectName("valueLabel_10")
        self.gridLayout_3.addWidget(self.valueLabel_10, 0, 1, 1, 1)
        self.valueLabel_11 = QtWidgets.QLabel(self.centralwidget)
        self.valueLabel_11.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.valueLabel_11.setFont(font)
        self.valueLabel_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.valueLabel_11.setAlignment(QtCore.Qt.AlignCenter)
        self.valueLabel_11.setObjectName("valueLabel_11")
        self.gridLayout_3.addWidget(self.valueLabel_11, 0, 2, 1, 1)
        self.valueLabel_12 = QtWidgets.QLabel(self.centralwidget)
        self.valueLabel_12.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.valueLabel_12.setFont(font)
        self.valueLabel_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.valueLabel_12.setAlignment(QtCore.Qt.AlignCenter)
        self.valueLabel_12.setObjectName("valueLabel_12")
        self.gridLayout_3.addWidget(self.valueLabel_12, 0, 3, 1, 1)
        self.portText_9 = QtWidgets.QTextEdit(self.centralwidget)
        self.portText_9.setObjectName("portText_9")
        self.gridLayout_3.addWidget(self.portText_9, 1, 0, 1, 1)
        self.portText_10 = QtWidgets.QTextEdit(self.centralwidget)
        self.portText_10.setObjectName("portText_10")
        self.gridLayout_3.addWidget(self.portText_10, 1, 1, 1, 1)
        self.portText_11 = QtWidgets.QTextEdit(self.centralwidget)
        self.portText_11.setObjectName("portText_11")
        self.gridLayout_3.addWidget(self.portText_11, 1, 2, 1, 1)
        self.portText_12 = QtWidgets.QTextEdit(self.centralwidget)
        self.portText_12.setObjectName("portText_12")
        self.gridLayout_3.addWidget(self.portText_12, 1, 3, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_3, 5, 0, 1, 1)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.portBox_17 = QtWidgets.QComboBox(self.centralwidget)
        self.portBox_17.setMaximumSize(QtCore.QSize(100, 16777215))
        self.portBox_17.setObjectName("portBox_17")
        self.horizontalLayout_17.addWidget(self.portBox_17)
        self.nameButton_17 = QtWidgets.QPushButton(self.centralwidget)
        self.nameButton_17.setObjectName("nameButton_17")
        self.horizontalLayout_17.addWidget(self.nameButton_17)
        self.sendButton_17 = QtWidgets.QPushButton(self.centralwidget)
        self.sendButton_17.setMaximumSize(QtCore.QSize(40, 16777215))
        self.sendButton_17.setObjectName("sendButton_17")
        self.horizontalLayout_17.addWidget(self.sendButton_17)
        self.muteButton_17 = QtWidgets.QPushButton(self.centralwidget)
        self.muteButton_17.setMaximumSize(QtCore.QSize(40, 16777215))
        self.muteButton_17.setObjectName("muteButton_17")
        self.horizontalLayout_17.addWidget(self.muteButton_17)
        self.gridLayout_5.addLayout(self.horizontalLayout_17, 2, 0, 1, 1)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.portBox_18 = QtWidgets.QComboBox(self.centralwidget)
        self.portBox_18.setMaximumSize(QtCore.QSize(100, 16777215))
        self.portBox_18.setObjectName("portBox_18")
        self.horizontalLayout_18.addWidget(self.portBox_18)
        self.nameButton_18 = QtWidgets.QPushButton(self.centralwidget)
        self.nameButton_18.setObjectName("nameButton_18")
        self.horizontalLayout_18.addWidget(self.nameButton_18)
        self.sendButton_18 = QtWidgets.QPushButton(self.centralwidget)
        self.sendButton_18.setMaximumSize(QtCore.QSize(40, 16777215))
        self.sendButton_18.setObjectName("sendButton_18")
        self.horizontalLayout_18.addWidget(self.sendButton_18)
        self.muteButton_18 = QtWidgets.QPushButton(self.centralwidget)
        self.muteButton_18.setMaximumSize(QtCore.QSize(40, 16777215))
        self.muteButton_18.setObjectName("muteButton_18")
        self.horizontalLayout_18.addWidget(self.muteButton_18)
        self.gridLayout_5.addLayout(self.horizontalLayout_18, 2, 1, 1, 1)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.portBox_19 = QtWidgets.QComboBox(self.centralwidget)
        self.portBox_19.setMaximumSize(QtCore.QSize(100, 16777215))
        self.portBox_19.setObjectName("portBox_19")
        self.horizontalLayout_19.addWidget(self.portBox_19)
        self.nameButton_19 = QtWidgets.QPushButton(self.centralwidget)
        self.nameButton_19.setObjectName("nameButton_19")
        self.horizontalLayout_19.addWidget(self.nameButton_19)
        self.sendButton_19 = QtWidgets.QPushButton(self.centralwidget)
        self.sendButton_19.setMaximumSize(QtCore.QSize(40, 16777215))
        self.sendButton_19.setObjectName("sendButton_19")
        self.horizontalLayout_19.addWidget(self.sendButton_19)
        self.muteButton_19 = QtWidgets.QPushButton(self.centralwidget)
        self.muteButton_19.setMaximumSize(QtCore.QSize(40, 16777215))
        self.muteButton_19.setObjectName("muteButton_19")
        self.horizontalLayout_19.addWidget(self.muteButton_19)
        self.gridLayout_5.addLayout(self.horizontalLayout_19, 2, 2, 1, 1)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.portBox_20 = QtWidgets.QComboBox(self.centralwidget)
        self.portBox_20.setMaximumSize(QtCore.QSize(100, 16777215))
        self.portBox_20.setObjectName("portBox_20")
        self.horizontalLayout_20.addWidget(self.portBox_20)
        self.nameButton_20 = QtWidgets.QPushButton(self.centralwidget)
        self.nameButton_20.setObjectName("nameButton_20")
        self.horizontalLayout_20.addWidget(self.nameButton_20)
        self.sendButton_20 = QtWidgets.QPushButton(self.centralwidget)
        self.sendButton_20.setMaximumSize(QtCore.QSize(40, 16777215))
        self.sendButton_20.setObjectName("sendButton_20")
        self.horizontalLayout_20.addWidget(self.sendButton_20)
        self.muteButton_20 = QtWidgets.QPushButton(self.centralwidget)
        self.muteButton_20.setMaximumSize(QtCore.QSize(40, 16777215))
        self.muteButton_20.setObjectName("muteButton_20")
        self.horizontalLayout_20.addWidget(self.muteButton_20)
        self.gridLayout_5.addLayout(self.horizontalLayout_20, 2, 3, 1, 1)
        self.valueLabel_17 = QtWidgets.QLabel(self.centralwidget)
        self.valueLabel_17.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.valueLabel_17.setFont(font)
        self.valueLabel_17.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.valueLabel_17.setAlignment(QtCore.Qt.AlignCenter)
        self.valueLabel_17.setObjectName("valueLabel_17")
        self.gridLayout_5.addWidget(self.valueLabel_17, 0, 0, 1, 1)
        self.valueLabel_18 = QtWidgets.QLabel(self.centralwidget)
        self.valueLabel_18.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.valueLabel_18.setFont(font)
        self.valueLabel_18.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.valueLabel_18.setAlignment(QtCore.Qt.AlignCenter)
        self.valueLabel_18.setObjectName("valueLabel_18")
        self.gridLayout_5.addWidget(self.valueLabel_18, 0, 1, 1, 1)
        self.valueLabel_19 = QtWidgets.QLabel(self.centralwidget)
        self.valueLabel_19.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.valueLabel_19.setFont(font)
        self.valueLabel_19.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.valueLabel_19.setAlignment(QtCore.Qt.AlignCenter)
        self.valueLabel_19.setObjectName("valueLabel_19")
        self.gridLayout_5.addWidget(self.valueLabel_19, 0, 2, 1, 1)
        self.valueLabel_20 = QtWidgets.QLabel(self.centralwidget)
        self.valueLabel_20.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.valueLabel_20.setFont(font)
        self.valueLabel_20.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.valueLabel_20.setAlignment(QtCore.Qt.AlignCenter)
        self.valueLabel_20.setObjectName("valueLabel_20")
        self.gridLayout_5.addWidget(self.valueLabel_20, 0, 3, 1, 1)
        self.portText_17 = QtWidgets.QTextEdit(self.centralwidget)
        self.portText_17.setObjectName("portText_17")
        self.gridLayout_5.addWidget(self.portText_17, 1, 0, 1, 1)
        self.portText_18 = QtWidgets.QTextEdit(self.centralwidget)
        self.portText_18.setObjectName("portText_18")
        self.gridLayout_5.addWidget(self.portText_18, 1, 1, 1, 1)
        self.portText_19 = QtWidgets.QTextEdit(self.centralwidget)
        self.portText_19.setObjectName("portText_19")
        self.gridLayout_5.addWidget(self.portText_19, 1, 2, 1, 1)
        self.portText_20 = QtWidgets.QTextEdit(self.centralwidget)
        self.portText_20.setObjectName("portText_20")
        self.gridLayout_5.addWidget(self.portText_20, 1, 3, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_5, 7, 0, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.portBox_5 = QtWidgets.QComboBox(self.centralwidget)
        self.portBox_5.setMaximumSize(QtCore.QSize(100, 16777215))
        self.portBox_5.setObjectName("portBox_5")
        self.horizontalLayout_5.addWidget(self.portBox_5)
        self.nameButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.nameButton_5.setObjectName("nameButton_5")
        self.horizontalLayout_5.addWidget(self.nameButton_5)
        self.sendButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.sendButton_5.setMaximumSize(QtCore.QSize(40, 16777215))
        self.sendButton_5.setObjectName("sendButton_5")
        self.horizontalLayout_5.addWidget(self.sendButton_5)
        self.muteButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.muteButton_5.setMaximumSize(QtCore.QSize(40, 16777215))
        self.muteButton_5.setObjectName("muteButton_5")
        self.horizontalLayout_5.addWidget(self.muteButton_5)
        self.gridLayout_2.addLayout(self.horizontalLayout_5, 2, 0, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.portBox_6 = QtWidgets.QComboBox(self.centralwidget)
        self.portBox_6.setMaximumSize(QtCore.QSize(100, 16777215))
        self.portBox_6.setObjectName("portBox_6")
        self.horizontalLayout_6.addWidget(self.portBox_6)
        self.nameButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.nameButton_6.setObjectName("nameButton_6")
        self.horizontalLayout_6.addWidget(self.nameButton_6)
        self.sendButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.sendButton_6.setMaximumSize(QtCore.QSize(40, 16777215))
        self.sendButton_6.setObjectName("sendButton_6")
        self.horizontalLayout_6.addWidget(self.sendButton_6)
        self.muteButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.muteButton_6.setMaximumSize(QtCore.QSize(40, 16777215))
        self.muteButton_6.setObjectName("muteButton_6")
        self.horizontalLayout_6.addWidget(self.muteButton_6)
        self.gridLayout_2.addLayout(self.horizontalLayout_6, 2, 1, 1, 1)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.portBox_7 = QtWidgets.QComboBox(self.centralwidget)
        self.portBox_7.setMaximumSize(QtCore.QSize(100, 16777215))
        self.portBox_7.setObjectName("portBox_7")
        self.horizontalLayout_7.addWidget(self.portBox_7)
        self.nameButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.nameButton_7.setObjectName("nameButton_7")
        self.horizontalLayout_7.addWidget(self.nameButton_7)
        self.sendButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.sendButton_7.setMaximumSize(QtCore.QSize(40, 16777215))
        self.sendButton_7.setObjectName("sendButton_7")
        self.horizontalLayout_7.addWidget(self.sendButton_7)
        self.muteButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.muteButton_7.setMaximumSize(QtCore.QSize(40, 16777215))
        self.muteButton_7.setObjectName("muteButton_7")
        self.horizontalLayout_7.addWidget(self.muteButton_7)
        self.gridLayout_2.addLayout(self.horizontalLayout_7, 2, 2, 1, 1)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.portBox_8 = QtWidgets.QComboBox(self.centralwidget)
        self.portBox_8.setMaximumSize(QtCore.QSize(100, 16777215))
        self.portBox_8.setObjectName("portBox_8")
        self.horizontalLayout_8.addWidget(self.portBox_8)
        self.nameButton_8 = QtWidgets.QPushButton(self.centralwidget)
        self.nameButton_8.setObjectName("nameButton_8")
        self.horizontalLayout_8.addWidget(self.nameButton_8)
        self.sendButton_8 = QtWidgets.QPushButton(self.centralwidget)
        self.sendButton_8.setMaximumSize(QtCore.QSize(40, 16777215))
        self.sendButton_8.setObjectName("sendButton_8")
        self.horizontalLayout_8.addWidget(self.sendButton_8)
        self.muteButton_8 = QtWidgets.QPushButton(self.centralwidget)
        self.muteButton_8.setMaximumSize(QtCore.QSize(40, 16777215))
        self.muteButton_8.setObjectName("muteButton_8")
        self.horizontalLayout_8.addWidget(self.muteButton_8)
        self.gridLayout_2.addLayout(self.horizontalLayout_8, 2, 3, 1, 1)
        self.valueLabel_5 = QtWidgets.QLabel(self.centralwidget)
        self.valueLabel_5.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.valueLabel_5.setFont(font)
        self.valueLabel_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.valueLabel_5.setAlignment(QtCore.Qt.AlignCenter)
        self.valueLabel_5.setObjectName("valueLabel_5")
        self.gridLayout_2.addWidget(self.valueLabel_5, 0, 0, 1, 1)
        self.valueLabel_6 = QtWidgets.QLabel(self.centralwidget)
        self.valueLabel_6.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.valueLabel_6.setFont(font)
        self.valueLabel_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.valueLabel_6.setAlignment(QtCore.Qt.AlignCenter)
        self.valueLabel_6.setObjectName("valueLabel_6")
        self.gridLayout_2.addWidget(self.valueLabel_6, 0, 1, 1, 1)
        self.valueLabel_7 = QtWidgets.QLabel(self.centralwidget)
        self.valueLabel_7.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.valueLabel_7.setFont(font)
        self.valueLabel_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.valueLabel_7.setAlignment(QtCore.Qt.AlignCenter)
        self.valueLabel_7.setObjectName("valueLabel_7")
        self.gridLayout_2.addWidget(self.valueLabel_7, 0, 2, 1, 1)
        self.valueLabel_8 = QtWidgets.QLabel(self.centralwidget)
        self.valueLabel_8.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.valueLabel_8.setFont(font)
        self.valueLabel_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.valueLabel_8.setAlignment(QtCore.Qt.AlignCenter)
        self.valueLabel_8.setObjectName("valueLabel_8")
        self.gridLayout_2.addWidget(self.valueLabel_8, 0, 3, 1, 1)
        self.portText_5 = QtWidgets.QTextEdit(self.centralwidget)
        self.portText_5.setObjectName("portText_5")
        self.gridLayout_2.addWidget(self.portText_5, 1, 0, 1, 1)
        self.portText_6 = QtWidgets.QTextEdit(self.centralwidget)
        self.portText_6.setObjectName("portText_6")
        self.gridLayout_2.addWidget(self.portText_6, 1, 1, 1, 1)
        self.portText_7 = QtWidgets.QTextEdit(self.centralwidget)
        self.portText_7.setObjectName("portText_7")
        self.gridLayout_2.addWidget(self.portText_7, 1, 2, 1, 1)
        self.portText_8 = QtWidgets.QTextEdit(self.centralwidget)
        self.portText_8.setObjectName("portText_8")
        self.gridLayout_2.addWidget(self.portText_8, 1, 3, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_2, 4, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.portBox = QtWidgets.QComboBox(self.centralwidget)
        self.portBox.setMaximumSize(QtCore.QSize(100, 16777215))
        self.portBox.setObjectName("portBox")
        self.horizontalLayout.addWidget(self.portBox)
        self.nameButton = QtWidgets.QPushButton(self.centralwidget)
        self.nameButton.setObjectName("nameButton")
        self.horizontalLayout.addWidget(self.nameButton)
        self.sendButton = QtWidgets.QPushButton(self.centralwidget)
        self.sendButton.setMaximumSize(QtCore.QSize(40, 16777215))
        self.sendButton.setObjectName("sendButton")
        self.horizontalLayout.addWidget(self.sendButton)
        self.muteButton = QtWidgets.QPushButton(self.centralwidget)
        self.muteButton.setMaximumSize(QtCore.QSize(40, 16777215))
        self.muteButton.setObjectName("muteButton")
        self.horizontalLayout.addWidget(self.muteButton)
        self.gridLayout.addLayout(self.horizontalLayout, 2, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.portBox_2 = QtWidgets.QComboBox(self.centralwidget)
        self.portBox_2.setMaximumSize(QtCore.QSize(100, 16777215))
        self.portBox_2.setObjectName("portBox_2")
        self.horizontalLayout_2.addWidget(self.portBox_2)
        self.nameButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.nameButton_2.setObjectName("nameButton_2")
        self.horizontalLayout_2.addWidget(self.nameButton_2)
        self.sendButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.sendButton_2.setMaximumSize(QtCore.QSize(40, 16777215))
        self.sendButton_2.setObjectName("sendButton_2")
        self.horizontalLayout_2.addWidget(self.sendButton_2)
        self.muteButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.muteButton_2.setMaximumSize(QtCore.QSize(40, 16777215))
        self.muteButton_2.setObjectName("muteButton_2")
        self.horizontalLayout_2.addWidget(self.muteButton_2)
        self.gridLayout.addLayout(self.horizontalLayout_2, 2, 1, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.portBox_3 = QtWidgets.QComboBox(self.centralwidget)
        self.portBox_3.setMaximumSize(QtCore.QSize(100, 16777215))
        self.portBox_3.setObjectName("portBox_3")
        self.horizontalLayout_3.addWidget(self.portBox_3)
        self.nameButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.nameButton_3.setObjectName("nameButton_3")
        self.horizontalLayout_3.addWidget(self.nameButton_3)
        self.sendButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.sendButton_3.setMaximumSize(QtCore.QSize(40, 16777215))
        self.sendButton_3.setObjectName("sendButton_3")
        self.horizontalLayout_3.addWidget(self.sendButton_3)
        self.muteButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.muteButton_3.setMaximumSize(QtCore.QSize(40, 16777215))
        self.muteButton_3.setObjectName("muteButton_3")
        self.horizontalLayout_3.addWidget(self.muteButton_3)
        self.gridLayout.addLayout(self.horizontalLayout_3, 2, 2, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.portBox_4 = QtWidgets.QComboBox(self.centralwidget)
        self.portBox_4.setMaximumSize(QtCore.QSize(100, 16777215))
        self.portBox_4.setObjectName("portBox_4")
        self.horizontalLayout_4.addWidget(self.portBox_4)
        self.nameButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.nameButton_4.setObjectName("nameButton_4")
        self.horizontalLayout_4.addWidget(self.nameButton_4)
        self.sendButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.sendButton_4.setMaximumSize(QtCore.QSize(40, 16777215))
        self.sendButton_4.setObjectName("sendButton_4")
        self.horizontalLayout_4.addWidget(self.sendButton_4)
        self.muteButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.muteButton_4.setMaximumSize(QtCore.QSize(40, 16777215))
        self.muteButton_4.setObjectName("muteButton_4")
        self.horizontalLayout_4.addWidget(self.muteButton_4)
        self.gridLayout.addLayout(self.horizontalLayout_4, 2, 3, 1, 1)
        self.valueLabel = QtWidgets.QLabel(self.centralwidget)
        self.valueLabel.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.valueLabel.setFont(font)
        self.valueLabel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.valueLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.valueLabel.setObjectName("valueLabel")
        self.gridLayout.addWidget(self.valueLabel, 0, 0, 1, 1)
        self.valueLabel_2 = QtWidgets.QLabel(self.centralwidget)
        self.valueLabel_2.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.valueLabel_2.setFont(font)
        self.valueLabel_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.valueLabel_2.setAlignment(QtCore.Qt.AlignCenter)
        self.valueLabel_2.setObjectName("valueLabel_2")
        self.gridLayout.addWidget(self.valueLabel_2, 0, 1, 1, 1)
        self.valueLabel_3 = QtWidgets.QLabel(self.centralwidget)
        self.valueLabel_3.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.valueLabel_3.setFont(font)
        self.valueLabel_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.valueLabel_3.setAlignment(QtCore.Qt.AlignCenter)
        self.valueLabel_3.setObjectName("valueLabel_3")
        self.gridLayout.addWidget(self.valueLabel_3, 0, 2, 1, 1)
        self.valueLabel_4 = QtWidgets.QLabel(self.centralwidget)
        self.valueLabel_4.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.valueLabel_4.setFont(font)
        self.valueLabel_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.valueLabel_4.setAlignment(QtCore.Qt.AlignCenter)
        self.valueLabel_4.setObjectName("valueLabel_4")
        self.gridLayout.addWidget(self.valueLabel_4, 0, 3, 1, 1)
        self.portText = QtWidgets.QTextEdit(self.centralwidget)
        self.portText.setObjectName("portText")
        self.gridLayout.addWidget(self.portText, 1, 0, 1, 1)
        self.portText_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.portText_2.setObjectName("portText_2")
        self.gridLayout.addWidget(self.portText_2, 1, 1, 1, 1)
        self.portText_3 = QtWidgets.QTextEdit(self.centralwidget)
        self.portText_3.setObjectName("portText_3")
        self.gridLayout.addWidget(self.portText_3, 1, 2, 1, 1)
        self.portText_4 = QtWidgets.QTextEdit(self.centralwidget)
        self.portText_4.setObjectName("portText_4")
        self.gridLayout.addWidget(self.portText_4, 1, 3, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout, 3, 0, 1, 1)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.portBox_13 = QtWidgets.QComboBox(self.centralwidget)
        self.portBox_13.setMaximumSize(QtCore.QSize(100, 16777215))
        self.portBox_13.setObjectName("portBox_13")
        self.horizontalLayout_13.addWidget(self.portBox_13)
        self.nameButton_13 = QtWidgets.QPushButton(self.centralwidget)
        self.nameButton_13.setObjectName("nameButton_13")
        self.horizontalLayout_13.addWidget(self.nameButton_13)
        self.sendButton_13 = QtWidgets.QPushButton(self.centralwidget)
        self.sendButton_13.setMaximumSize(QtCore.QSize(40, 16777215))
        self.sendButton_13.setObjectName("sendButton_13")
        self.horizontalLayout_13.addWidget(self.sendButton_13)
        self.muteButton_13 = QtWidgets.QPushButton(self.centralwidget)
        self.muteButton_13.setMaximumSize(QtCore.QSize(40, 16777215))
        self.muteButton_13.setObjectName("muteButton_13")
        self.horizontalLayout_13.addWidget(self.muteButton_13)
        self.gridLayout_4.addLayout(self.horizontalLayout_13, 2, 0, 1, 1)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.portBox_14 = QtWidgets.QComboBox(self.centralwidget)
        self.portBox_14.setMaximumSize(QtCore.QSize(100, 16777215))
        self.portBox_14.setObjectName("portBox_14")
        self.horizontalLayout_14.addWidget(self.portBox_14)
        self.nameButton_14 = QtWidgets.QPushButton(self.centralwidget)
        self.nameButton_14.setObjectName("nameButton_14")
        self.horizontalLayout_14.addWidget(self.nameButton_14)
        self.sendButton_14 = QtWidgets.QPushButton(self.centralwidget)
        self.sendButton_14.setMaximumSize(QtCore.QSize(40, 16777215))
        self.sendButton_14.setObjectName("sendButton_14")
        self.horizontalLayout_14.addWidget(self.sendButton_14)
        self.muteButton_14 = QtWidgets.QPushButton(self.centralwidget)
        self.muteButton_14.setMaximumSize(QtCore.QSize(40, 16777215))
        self.muteButton_14.setObjectName("muteButton_14")
        self.horizontalLayout_14.addWidget(self.muteButton_14)
        self.gridLayout_4.addLayout(self.horizontalLayout_14, 2, 1, 1, 1)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.portBox_15 = QtWidgets.QComboBox(self.centralwidget)
        self.portBox_15.setMaximumSize(QtCore.QSize(100, 16777215))
        self.portBox_15.setObjectName("portBox_15")
        self.horizontalLayout_15.addWidget(self.portBox_15)
        self.nameButton_15 = QtWidgets.QPushButton(self.centralwidget)
        self.nameButton_15.setObjectName("nameButton_15")
        self.horizontalLayout_15.addWidget(self.nameButton_15)
        self.sendButton_15 = QtWidgets.QPushButton(self.centralwidget)
        self.sendButton_15.setMaximumSize(QtCore.QSize(40, 16777215))
        self.sendButton_15.setObjectName("sendButton_15")
        self.horizontalLayout_15.addWidget(self.sendButton_15)
        self.muteButton_15 = QtWidgets.QPushButton(self.centralwidget)
        self.muteButton_15.setMaximumSize(QtCore.QSize(40, 16777215))
        self.muteButton_15.setObjectName("muteButton_15")
        self.horizontalLayout_15.addWidget(self.muteButton_15)
        self.gridLayout_4.addLayout(self.horizontalLayout_15, 2, 2, 1, 1)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.portBox_16 = QtWidgets.QComboBox(self.centralwidget)
        self.portBox_16.setMaximumSize(QtCore.QSize(100, 16777215))
        self.portBox_16.setObjectName("portBox_16")
        self.horizontalLayout_16.addWidget(self.portBox_16)
        self.nameButton_16 = QtWidgets.QPushButton(self.centralwidget)
        self.nameButton_16.setObjectName("nameButton_16")
        self.horizontalLayout_16.addWidget(self.nameButton_16)
        self.sendButton_16 = QtWidgets.QPushButton(self.centralwidget)
        self.sendButton_16.setMaximumSize(QtCore.QSize(40, 16777215))
        self.sendButton_16.setObjectName("sendButton_16")
        self.horizontalLayout_16.addWidget(self.sendButton_16)
        self.muteButton_16 = QtWidgets.QPushButton(self.centralwidget)
        self.muteButton_16.setMaximumSize(QtCore.QSize(40, 16777215))
        self.muteButton_16.setObjectName("muteButton_16")
        self.horizontalLayout_16.addWidget(self.muteButton_16)
        self.gridLayout_4.addLayout(self.horizontalLayout_16, 2, 3, 1, 1)
        self.valueLabel_13 = QtWidgets.QLabel(self.centralwidget)
        self.valueLabel_13.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.valueLabel_13.setFont(font)
        self.valueLabel_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.valueLabel_13.setAlignment(QtCore.Qt.AlignCenter)
        self.valueLabel_13.setObjectName("valueLabel_13")
        self.gridLayout_4.addWidget(self.valueLabel_13, 0, 0, 1, 1)
        self.valueLabel_14 = QtWidgets.QLabel(self.centralwidget)
        self.valueLabel_14.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.valueLabel_14.setFont(font)
        self.valueLabel_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.valueLabel_14.setAlignment(QtCore.Qt.AlignCenter)
        self.valueLabel_14.setObjectName("valueLabel_14")
        self.gridLayout_4.addWidget(self.valueLabel_14, 0, 1, 1, 1)
        self.valueLabel_15 = QtWidgets.QLabel(self.centralwidget)
        self.valueLabel_15.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.valueLabel_15.setFont(font)
        self.valueLabel_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.valueLabel_15.setAlignment(QtCore.Qt.AlignCenter)
        self.valueLabel_15.setObjectName("valueLabel_15")
        self.gridLayout_4.addWidget(self.valueLabel_15, 0, 2, 1, 1)
        self.valueLabel_16 = QtWidgets.QLabel(self.centralwidget)
        self.valueLabel_16.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.valueLabel_16.setFont(font)
        self.valueLabel_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.valueLabel_16.setAlignment(QtCore.Qt.AlignCenter)
        self.valueLabel_16.setObjectName("valueLabel_16")
        self.gridLayout_4.addWidget(self.valueLabel_16, 0, 3, 1, 1)
        self.portText_13 = QtWidgets.QTextEdit(self.centralwidget)
        self.portText_13.setObjectName("portText_13")
        self.gridLayout_4.addWidget(self.portText_13, 1, 0, 1, 1)
        self.portText_14 = QtWidgets.QTextEdit(self.centralwidget)
        self.portText_14.setObjectName("portText_14")
        self.gridLayout_4.addWidget(self.portText_14, 1, 1, 1, 1)
        self.portText_15 = QtWidgets.QTextEdit(self.centralwidget)
        self.portText_15.setObjectName("portText_15")
        self.gridLayout_4.addWidget(self.portText_15, 1, 2, 1, 1)
        self.portText_16 = QtWidgets.QTextEdit(self.centralwidget)
        self.portText_16.setObjectName("portText_16")
        self.gridLayout_4.addWidget(self.portText_16, 1, 3, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_4, 6, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem1, 2, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1319, 21))
        self.menubar.setObjectName("menubar")
        self.menuSETTINGS = QtWidgets.QMenu(self.menubar)
        self.menuSETTINGS.setObjectName("menuSETTINGS")
        self.menuLOG = QtWidgets.QMenu(self.menuSETTINGS)
        self.menuLOG.setObjectName("menuLOG")
        self.menuSettings = QtWidgets.QMenu(self.menuSETTINGS)
        self.menuSettings.setObjectName("menuSettings")
        self.menuLog_write = QtWidgets.QMenu(self.menuSettings)
        self.menuLog_write.setObjectName("menuLog_write")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actiongdhsd = QtWidgets.QAction(MainWindow)
        self.actiongdhsd.setObjectName("actiongdhsd")
        self.viewLog_prog = QtWidgets.QAction(MainWindow)
        self.viewLog_prog.setCheckable(False)
        self.viewLog_prog.setObjectName("viewLog_prog")
        self.viewLog_port = QtWidgets.QAction(MainWindow)
        self.viewLog_port.setCheckable(False)
        self.viewLog_port.setObjectName("viewLog_port")
        self.viewLog_sens = QtWidgets.QAction(MainWindow)
        self.viewLog_sens.setCheckable(False)
        self.viewLog_sens.setObjectName("viewLog_sens")
        self.setVoice_on = QtWidgets.QAction(MainWindow)
        self.setVoice_on.setCheckable(True)
        self.setVoice_on.setMenuRole(QtWidgets.QAction.NoRole)
        self.setVoice_on.setObjectName("setVoice_on")
        self.setSound_on = QtWidgets.QAction(MainWindow)
        self.setSound_on.setCheckable(True)
        self.setSound_on.setObjectName("setSound_on")
        self.setData_write = QtWidgets.QAction(MainWindow)
        self.setData_write.setCheckable(True)
        self.setData_write.setObjectName("setData_write")
        self.writeLog_prog = QtWidgets.QAction(MainWindow)
        self.writeLog_prog.setCheckable(True)
        self.writeLog_prog.setObjectName("writeLog_prog")
        self.writeLog_port = QtWidgets.QAction(MainWindow)
        self.writeLog_port.setCheckable(True)
        self.writeLog_port.setObjectName("writeLog_port")
        self.writeLog_sens = QtWidgets.QAction(MainWindow)
        self.writeLog_sens.setCheckable(True)
        self.writeLog_sens.setObjectName("writeLog_sens")
        self.menuLOG.addAction(self.viewLog_prog)
        self.menuLOG.addAction(self.viewLog_port)
        self.menuLOG.addAction(self.viewLog_sens)
        self.menuLog_write.addAction(self.writeLog_prog)
        self.menuLog_write.addAction(self.writeLog_port)
        self.menuLog_write.addAction(self.writeLog_sens)
        self.menuSettings.addAction(self.setVoice_on)
        self.menuSettings.addAction(self.setSound_on)
        self.menuSettings.addAction(self.setData_write)
        self.menuSettings.addAction(self.menuLog_write.menuAction())
        self.menuSETTINGS.addAction(self.menuSettings.menuAction())
        self.menuSETTINGS.addAction(self.menuLOG.menuAction())
        self.menubar.addAction(self.menuSETTINGS.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.topPushButton.setText(_translate("MainWindow", "PushButton"))
        self.topPushButton_2.setText(_translate("MainWindow", "PushButton"))
        self.resetButton.setText(_translate("MainWindow", "RESET"))
        self.applyButton.setText(_translate("MainWindow", "Apply"))
        self.timeLabel.setText(_translate("MainWindow", "TIME"))
        self.nameButton_9.setText(_translate("MainWindow", "NAME"))
        self.sendButton_9.setText(_translate("MainWindow", "SEND"))
        self.muteButton_9.setText(_translate("MainWindow", "MUTE"))
        self.nameButton_10.setText(_translate("MainWindow", "NAME"))
        self.sendButton_10.setText(_translate("MainWindow", "SEND"))
        self.muteButton_10.setText(_translate("MainWindow", "MUTE"))
        self.nameButton_11.setText(_translate("MainWindow", "NAME"))
        self.sendButton_11.setText(_translate("MainWindow", "SEND"))
        self.muteButton_11.setText(_translate("MainWindow", "MUTE"))
        self.nameButton_12.setText(_translate("MainWindow", "NAME"))
        self.sendButton_12.setText(_translate("MainWindow", "SEND"))
        self.muteButton_12.setText(_translate("MainWindow", "MUTE"))
        self.valueLabel_9.setText(_translate("MainWindow", "VALUE"))
        self.valueLabel_10.setText(_translate("MainWindow", "VALUE"))
        self.valueLabel_11.setText(_translate("MainWindow", "VALUE"))
        self.valueLabel_12.setText(_translate("MainWindow", "VALUE"))
        self.nameButton_17.setText(_translate("MainWindow", "NAME"))
        self.sendButton_17.setText(_translate("MainWindow", "SEND"))
        self.muteButton_17.setText(_translate("MainWindow", "MUTE"))
        self.nameButton_18.setText(_translate("MainWindow", "NAME"))
        self.sendButton_18.setText(_translate("MainWindow", "SEND"))
        self.muteButton_18.setText(_translate("MainWindow", "MUTE"))
        self.nameButton_19.setText(_translate("MainWindow", "NAME"))
        self.sendButton_19.setText(_translate("MainWindow", "SEND"))
        self.muteButton_19.setText(_translate("MainWindow", "MUTE"))
        self.nameButton_20.setText(_translate("MainWindow", "NAME"))
        self.sendButton_20.setText(_translate("MainWindow", "SEND"))
        self.muteButton_20.setText(_translate("MainWindow", "MUTE"))
        self.valueLabel_17.setText(_translate("MainWindow", "VALUE"))
        self.valueLabel_18.setText(_translate("MainWindow", "VALUE"))
        self.valueLabel_19.setText(_translate("MainWindow", "VALUE"))
        self.valueLabel_20.setText(_translate("MainWindow", "VALUE"))
        self.nameButton_5.setText(_translate("MainWindow", "NAME"))
        self.sendButton_5.setText(_translate("MainWindow", "SEND"))
        self.muteButton_5.setText(_translate("MainWindow", "MUTE"))
        self.nameButton_6.setText(_translate("MainWindow", "NAME"))
        self.sendButton_6.setText(_translate("MainWindow", "SEND"))
        self.muteButton_6.setText(_translate("MainWindow", "MUTE"))
        self.nameButton_7.setText(_translate("MainWindow", "NAME"))
        self.sendButton_7.setText(_translate("MainWindow", "SEND"))
        self.muteButton_7.setText(_translate("MainWindow", "MUTE"))
        self.nameButton_8.setText(_translate("MainWindow", "NAME"))
        self.sendButton_8.setText(_translate("MainWindow", "SEND"))
        self.muteButton_8.setText(_translate("MainWindow", "MUTE"))
        self.valueLabel_5.setText(_translate("MainWindow", "VALUE"))
        self.valueLabel_6.setText(_translate("MainWindow", "VALUE"))
        self.valueLabel_7.setText(_translate("MainWindow", "VALUE"))
        self.valueLabel_8.setText(_translate("MainWindow", "VALUE"))
        self.nameButton.setText(_translate("MainWindow", "NAME"))
        self.sendButton.setText(_translate("MainWindow", "SEND"))
        self.muteButton.setText(_translate("MainWindow", "MUTE"))
        self.nameButton_2.setText(_translate("MainWindow", "NAME"))
        self.sendButton_2.setText(_translate("MainWindow", "SEND"))
        self.muteButton_2.setText(_translate("MainWindow", "MUTE"))
        self.nameButton_3.setText(_translate("MainWindow", "NAME"))
        self.sendButton_3.setText(_translate("MainWindow", "SEND"))
        self.muteButton_3.setText(_translate("MainWindow", "MUTE"))
        self.nameButton_4.setText(_translate("MainWindow", "NAME"))
        self.sendButton_4.setText(_translate("MainWindow", "SEND"))
        self.muteButton_4.setText(_translate("MainWindow", "MUTE"))
        self.valueLabel.setText(_translate("MainWindow", "VALUE"))
        self.valueLabel_2.setText(_translate("MainWindow", "VALUE"))
        self.valueLabel_3.setText(_translate("MainWindow", "VALUE"))
        self.valueLabel_4.setText(_translate("MainWindow", "VALUE"))
        self.nameButton_13.setText(_translate("MainWindow", "NAME"))
        self.sendButton_13.setText(_translate("MainWindow", "SEND"))
        self.muteButton_13.setText(_translate("MainWindow", "MUTE"))
        self.nameButton_14.setText(_translate("MainWindow", "NAME"))
        self.sendButton_14.setText(_translate("MainWindow", "SEND"))
        self.muteButton_14.setText(_translate("MainWindow", "MUTE"))
        self.nameButton_15.setText(_translate("MainWindow", "NAME"))
        self.sendButton_15.setText(_translate("MainWindow", "SEND"))
        self.muteButton_15.setText(_translate("MainWindow", "MUTE"))
        self.nameButton_16.setText(_translate("MainWindow", "NAME"))
        self.sendButton_16.setText(_translate("MainWindow", "SEND"))
        self.muteButton_16.setText(_translate("MainWindow", "MUTE"))
        self.valueLabel_13.setText(_translate("MainWindow", "VALUE"))
        self.valueLabel_14.setText(_translate("MainWindow", "VALUE"))
        self.valueLabel_15.setText(_translate("MainWindow", "VALUE"))
        self.valueLabel_16.setText(_translate("MainWindow", "VALUE"))
        self.menuSETTINGS.setTitle(_translate("MainWindow", "MENU"))
        self.menuLOG.setTitle(_translate("MainWindow", "LOG"))
        self.menuSettings.setTitle(_translate("MainWindow", "Settings"))
        self.menuLog_write.setTitle(_translate("MainWindow", "Log write"))
        self.actiongdhsd.setText(_translate("MainWindow", "gdhsd"))
        self.viewLog_prog.setText(_translate("MainWindow", "Prog"))
        self.viewLog_port.setText(_translate("MainWindow", "Port"))
        self.viewLog_sens.setText(_translate("MainWindow", "Sens"))
        self.setVoice_on.setText(_translate("MainWindow", "Voice"))
        self.setSound_on.setText(_translate("MainWindow", "Sound alarm"))
        self.setData_write.setText(_translate("MainWindow", "Data write"))
        self.writeLog_prog.setText(_translate("MainWindow", "Prog"))
        self.writeLog_port.setText(_translate("MainWindow", "Port"))
        self.writeLog_sens.setText(_translate("MainWindow", "Sens"))


